### ISSUE TITLE
[che] Unable to create project. Failed to get template list

### ISSUE THREAD

**Issue by yangcao77** [eclipse/codewind#1177]
**Codewind version:** master
**OS:** MacOS

**Che version:** 7.3.1
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:** OKD

**Description:**
Unable to create project on che with the latest devfile.
Looks like failed to get template list
Saw this error in theia log:
```
root INFO [hosted-plugin: 41] [INFO: 16:23:50.346 CLIWrapper.js:110]: Running CLI command: cwctl --json --insecure templates repos list
root INFO [hosted-plugin: 41] [DBUG: 16:23:50.512 CLIWrapper.js.on():179]: Successfully ran CLI command cwctl --json --insecure templates repos list, Output was:
null
root ERROR [hosted-plugin: 41] [ERRO: 16:23:50.512 CLIWrapper.js.on():184]: Missing expected JSON output from CLI command, output was "null
"
[ERRO: 16:23:50.513 extension.js.on():44]: Unhandled promise rejection: TypeError: repos.map is not a function
    at /tmp/vscode-unpacked/eclipse.codewind-plugin.latest.uzzsdhhlzy.codewind-theia.vsix/extension/out/command/connection/CreateUserProjectCmd.js:155:28
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/vscode-unpacked/eclipse.codewind-plugin.latest.uzzsdhhlzy.codewind-theia.vsix/extension/out/command/connection/CreateUserProjectCmd.js:15:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
root ERROR [hosted-plugin: 41] Promise rejection not handled in one second: TypeError: repos.map is not a function
With stack trace: TypeError: repos.map is not a function
    at /tmp/vscode-unpacked/eclipse.codewind-plugin.latest.uzzsdhhlzy.codewind-theia.vsix/extension/out/command/connection/CreateUserProjectCmd.js:155:28
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/vscode-unpacked/eclipse.codewind-plugin.latest.uzzsdhhlzy.codewind-theia.vsix/extension/out/command/connection/CreateUserProjectCmd.js:15:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Steps to reproduce:**
try to open command `create project` on che

**Workaround:**

**Comment by yangcao77** [comment]
The error log says the output for `cwctl --json --insecure templates repos list` was null. 

But I'm able to see the templates repos list if I manually run this command inside sidecar
```
 $ cwctl --json --insecure templates repos list
[
	{
		"description": "Codewind project templates help you create containerized projects for various runtimes.",
		"url": "https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/index.json",
		"name": "Default templates",
		"id": "",
		"enabled": true,
		"protected": true,
		"projectStyles": [
			"Codewind"
		]
	},
	{
		"description": "The set of templates for new OpenShift projects in Codewind.",
		"url": "file:///codewind-workspace/.extensions/codewind-odo-extension/templates/index.json",
		"name": "OpenShift templates",
		"id": "",
		"enabled": true,
		"protected": true,
		"projectStyles": [
			"OpenShift"
		]
	},
	{
		"description": "Use Appsody in Codewind to develop applications with sharable technology stacks.",
		"url": "https://github.com/appsody/stacks/releases/latest/download/incubator-index.json",
		"name": "Appsody Stacks - incubator",
		"id": "incubator",
		"enabled": true,
		"protected": true,
		"projectStyles": [
			"Appsody"
		]
	}
]

```

**Comment by elsony** [comment]
@yangcao77 Is this problem specific to master or do you see the same problem on 0.6.0?

**Comment by johnmcollier** [comment]
@elsony @yangcao77 I can reproduce this on master only, 0.6.0 is fine for me

**Comment by tetchel** [comment]
i see this on my local machine when working against a remote connection

```
[INFO: 14:46:31.363 CLIWrapper.js:110]: Running CLI command: cwctl --json --insecure templates repos list --conid K320XGSI
[DBUG: 14:46:31.583 CLIWrapper.js:181]: Successfully ran CLI command cwctl --json --insecure templates repos list --conid K320XGSI, Output was:
null
[ERRO: 14:46:31.586 CLIWrapper.js:186]: Missing expected JSON output from CLI command, output was "null
"
[ERRO: 14:46:31.589 extension.js:44]: Unhandled promise rejection: TypeError: repos.map is not a function
	at buildTemplateTable (/Users/tim/programs/codewind-vscode/dev/out/command/webview/ManageTemplateReposPage.js:133:28)
	at Object.getManageReposPage [as default] (/Users/tim/programs/codewind-vscode/dev/out/command/webview/ManageTemplateReposPage.js:68:7)
	at /Users/tim/programs/codewind-vscode/dev/out/command/connection/ManageTemplateReposCmd.js:77:55
	at Generator.next (<anonymous>)
	at fulfilled (/Users/tim/programs/codewind-vscode/dev/out/command/connection/ManageTemplateReposCmd.js:15:58)
```

but it works when the conid is "local"

@james-wallis could this have been caused by https://github.com/eclipse/codewind-installer/pull/217, any theories

**Comment by tetchel** [comment]
it should never output "null", we should get an `{ error: string, error_description: string }` if anything is going wrong (as it clearly is)

**Comment by james-wallis** [comment]
I've been able to recreate this locally after updating the CLI to master using the command `cwctl --insecure templates repos list --conid K37BCNPK` (with and without the `--json` flag). Must have been a change that went in yesterday as I wan't seeing it when testing another PR.

**Comment by james-wallis** [comment]
@yangcao77 @johnmcollier I've got a local che instance running and have successfully created a Node.js project from the default templates.
Devfile link used was: `http://che-che.10.108.6.229.nip.io/f?url=https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/latest/devfile.yaml`

Could you provide further information on a type of project to create or please retest? Thanks

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/issues/1177#issuecomment-555185071 is fixed with eclipse/codewind-installer#227

**Comment by tetchel** [comment]
It works in Che too now, but it is very slow - 27 seconds!

```
root INFO [hosted-plugin: 113] [INFO: 17:25:52.930 CLIWrapper.js:110]: Running CLI command: cwctl --json --insecure templates repos list
root INFO [hosted-plugin: 113] [DBUG: 17:26:19.138 CLIWrapper.js.on():179]: Successfully ran CLI command cwctl --json --insecure templates repos list, Output was:
[
	{
		"description": "Codewind project templates help you create containerized projects for various runtimes.",
		"url": "https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/index.json",
		"name": "Default templates",
		"id": "",
		"enabled": true,
		"protected": true,
		"projectStyles": [
			"Codewind"
		]
	},
	{
		"description": "The set of templates for new OpenShift projects in Codewind.",
		"url": "file:///codewind-workspace/.extensions/codewind-odo-extension/templates/index.json",
		"name": "OpenShift templates",
		"id": "",
		"enabled": true,
		"protected": true,
		"projectStyles": [
			"OpenShift"
		]
	},
	{
		"description": "Use Appsody in Codewind to develop applications with sharable technology stacks.",
		"url": "https://github.com/appsody/stacks/releases/latest/download/incubator-index.json",
		"name": "Appsody Stacks - incubator",
		"id": "incubator",
		"enabled": true,
		"protected": true,
		"projectStyles": [
			"Appsody"
		]
	}
]
```

**Comment by yangcao77** [comment]
Confirmed this has been fixed on che. And no performance issue on my cluster. 
Closing this issue.
